<?php
// $Id$
/**
 * @file
 * TestVCS backend for Version Control API -
 * Helper for testing Version Control core
 */

/**
 * Implementation of hook_versioncontrol_backends().
 */
function versioncontrol_test_versioncontrol_backends() {
  return array(
    'test' => array(
      'name' => 'TestVCS',
      'description' => t('TestVCS backend for Version Control API.'),
      'capabilities' => array(),
      'flags' => array(),
    ),
  );
}
