<?php
// $Id$
/**
 * @file
 * TestVCS backend for Version Control API -
 * Helper for testing Version Control core
 */

require_once drupal_get_path('module', 'versioncontrol') . '/includes/VersioncontrolBackend.php';
require_once drupal_get_path('module', 'versioncontrol') . '/includes/VersioncontrolRepository.php';

/**
 * Implementation of hook_versioncontrol_backends().
 */
function versioncontrol_test_versioncontrol_backends() {
  return array(
    'test' => new VersioncontrolTestBackend(
      'TestVCS',
      t('TestVCS backend for Version Control API.'),
      array(),
      array(),
      array('repo' => 'VersioncontrolTestRepository')
    ),
  );
}

class VersioncontrolTestBackend extends VersioncontrolBackend {
}

class VersioncontrolTestRepository extends VersioncontrolRepository {
}
